### ISSUE TITLE
Guide (semi noob but not entirely)

### ISSUE THREAD

**Issue by Frikkie50** [gdwaterworth/Home-Assistant---E-Linter-Logger---Sunsynk#1]
Loving the fact that i can pull info no.

Do you have a guide on how to use the loadshedding / sunsynk timer changes? 

Love the work you have done.

**Comment by gdwaterworth** [comment]
Still a very new project and the automation atm is undergoing alot of change. 
There are a few dependencies on other addon/integrations.
Once things are a bit more stable and it is a bit more cleaned up I will document it

**Comment by Frikkie50** [comment]
Thanks man, loving what you have done. Lately the sunsynk site doesnt work for while

**Comment by gdwaterworth** [comment]
The e-linter site is down now and again for a few hours at a time. Trying to build in more error checking for it, but it is hard :/ 
Yesterday the "settings" were not being updated for about 3 hours.

**Comment by Frikkie50** [comment]
Perhaps one day they will open up the dongle to allow us to grab information from there

**Comment by CraigBoswell** [comment]
> Perhaps one day they will open up the dongle to allow us to grab information from there

So agree with you. I think I read somewhere it is open to Phillip's Hue, but I don't have one of those. Maybe if enough users pester Sunsynk they'll open it.

**Comment by gdwaterworth** [comment]
Pfft not holding my breath.

**Comment by Frikkie50** [comment]
any guide on doing v2.3?

**Comment by Frikkie50** [comment]
> any guide on doing v2.3?

Just ignore my comment got it installed. Clearly I missed the short guide.

**Comment by Frikkie50** [comment]
Thanks for all the hard work on this.
