### ISSUE TITLE
SunSynk Sysworkmode Helper does not update Inverter Work Mode

### ISSUE THREAD

**Issue by Ashleysbox** [gdwaterworth/Home-Assistant---E-Linter-Logger---Sunsynk#55]
Changing the value of the SunSynk Sysworkmode helper to any of 1, 2 or 3 does not appear to generate an update event.

All other Sunsynk Sensors and Helpers are working as expected.

**Comment by gdwaterworth** [comment]
Sysworkmode is not fully implemented yet

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Ashleysbox ***@***.***>
Sent: Wednesday, February 7, 2024 6:21:20 PM
To: gdwaterworth/Home-Assistant---E-Linter-Logger---Sunsynk ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gdwaterworth/Home-Assistant---E-Linter-Logger---Sunsynk] SunSynk Sysworkmode Helper does not update Inverter Work Mode (Issue #55)


Changing the value of the SunSynk Sysworkmode helper to any of 1, 2 or 3 does not appear to generate an update event.

All other Sunsynk Sensors and Helpers are working as expected.

**Comment by Ashleysbox** [comment]
Thanks so much for the quick reply and all your excellent work! 

If Sysworkmode can be implemented along with the Solar Export Toggle that will be more or less everything needed to manage UK smart tariffs and Demand Flexibility Service Events.

Well - if I were making a wish list I guess I could add Max Sell Power too 😉
